apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: sensors
  labels:
    apps.tanzu.vmware.com/workload-type: web
spec:
  source:
    git:
      url: https://github.com/dektlong/mood-sensors
      ref:
        branch: main
